import streamlit as st
import pandas as pd
import joblib
import json

from pathlib import Path
from datetime import datetime
from sklearn.utils.validation import check_is_fitted


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Retail Customer 360",
    page_icon="🛍️",
    layout="wide"
)


# ============================================================
# TITLE
# ============================================================

st.title("🛍️ Customer Insights & Repeat Purchase Predictor")

st.markdown(
    "Interactive Machine Learning dashboard for the Online Retail dataset."
)


# ============================================================
# FILE PATHS
# ============================================================

MODEL_PATH = Path("repeat_purchase_model_v2.pkl")

METADATA_PATH = Path("model_metadata.json")

LOG_PATH = Path("prediction_logs.csv")


# ============================================================
# LOAD MODEL METADATA
# ============================================================

@st.cache_data
def load_metadata():

    if not METADATA_PATH.exists():

        raise FileNotFoundError(
            f"Model metadata file not found: {METADATA_PATH}"
        )

    with open(METADATA_PATH, "r") as file:

        metadata = json.load(file)

    return metadata


try:

    metadata = load_metadata()

except Exception as e:

    st.error("❌ Failed to load model metadata.")

    st.exception(e)

    st.stop()


# ============================================================
# LOAD MODEL
# ============================================================

@st.cache_resource
def load_model():

    if not MODEL_PATH.exists():

        raise FileNotFoundError(
            f"Model file not found: {MODEL_PATH}"
        )

    model = joblib.load(MODEL_PATH)

    # Verify that the model is fitted
    check_is_fitted(model)

    return model


try:

    model = load_model()

except Exception as e:

    st.error("❌ Failed to load the trained model.")

    st.exception(e)

    st.stop()


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header("Customer Parameter Inputs")

st.sidebar.markdown(
    "Enter the customer's historical purchasing behavior."
)


recency_days = st.sidebar.number_input(
    "Recency Days",
    min_value=0.0,
    value=30.0,
    step=1.0,
    help="Number of days since the customer's last purchase."
)


frequency = st.sidebar.number_input(
    "Total Orders",
    min_value=1.0,
    value=5.0,
    step=1.0,
    help="Number of orders made by the customer."
)


total_items = st.sidebar.number_input(
    "Total Items Purchased",
    min_value=1.0,
    value=250.0,
    step=1.0,
    help="Total number of items purchased."
)


total_revenue = st.sidebar.number_input(
    "Total Revenue",
    min_value=0.0,
    value=1000.0,
    step=10.0,
    help="Total historical revenue generated by the customer."
)


average_transaction_value = st.sidebar.number_input(
    "Average Transaction Value",
    min_value=0.0,
    value=200.0,
    step=10.0,
    help="Average value of the customer's transactions."
)


unique_products = st.sidebar.number_input(
    "Unique Products",
    min_value=1.0,
    value=20.0,
    step=1.0,
    help="Number of different products purchased."
)


return_count = st.sidebar.number_input(
    "Return Count",
    min_value=0.0,
    value=0.0,
    step=1.0,
    help="Number of returns."
)


lifetime_days = st.sidebar.slider(
    "Customer Lifetime (Days)",
    min_value=0,
    max_value=730,
    value=180,
    help="Number of days between first and last purchase."
)


# ============================================================
# MODEL INFORMATION
# ============================================================

with st.sidebar.expander("🤖 Model Information"):

    st.write(
        f"**Model:** {metadata.get('model_name', 'N/A')}"
    )

    st.write(
        f"**Version:** {metadata.get('model_version', 'N/A')}"
    )

    st.write(
        f"**Algorithm:** {metadata.get('algorithm', 'N/A')}"
    )

    st.write(
        f"**Framework:** {metadata.get('framework', 'N/A')}"
    )

    st.write(
        f"**Target:** {metadata.get('target', 'N/A')}"
    )


# ============================================================
# PREDICTION
# ============================================================

st.subheader("Model Prediction")

st.write(
    "Predict whether this customer is likely to make a repeat purchase."
)


if st.button("🔮 Predict Repeat Purchase", type="primary"):

    # --------------------------------------------------------
    # Create input dataframe
    # --------------------------------------------------------

    input_data = pd.DataFrame({

        "recency_days": [recency_days],

        "frequency": [frequency],

        "total_items": [total_items],

        "total_revenue": [total_revenue],

        "average_transaction_value": [
            average_transaction_value
        ],

        "unique_products": [unique_products],

        "return_count": [return_count],

        "lifetime_days": [lifetime_days]

    })


    try:

        # ====================================================
        # PREDICTION
        # ====================================================

        prediction = model.predict(input_data)[0]


        # ====================================================
        # PROBABILITY
        # ====================================================

        probability = None

        if hasattr(model, "predict_proba"):

            probability = model.predict_proba(
                input_data
            )[0][1]


        # ====================================================
        # RESULT
        # ====================================================

        st.divider()

        if prediction == 1:

            st.success(
                "✅ **Likely to make a repeat purchase**"
            )

        else:

            st.warning(
                "⚠️ **Unlikely to make a repeat purchase**"
            )


        # ====================================================
        # METRICS
        # ====================================================

        if probability is not None:

            col1, col2 = st.columns(2)

            with col1:

                st.metric(
                    "Repeat Purchase Probability",
                    f"{probability:.1%}"
                )

            with col2:

                st.metric(
                    "Prediction",
                    "Repeat Purchase"
                    if prediction == 1
                    else "No Repeat Purchase"
                )

            st.progress(float(probability))


        # ====================================================
        # BUSINESS RECOMMENDATION
        # ====================================================

        st.subheader("💡 Business Recommendation")

        if probability is not None:

            if probability >= 0.75:

                st.success(
                    "High repeat-purchase potential. "
                    "Consider loyalty rewards, cross-selling, "
                    "or personalized recommendations."
                )

            elif probability >= 0.50:

                st.info(
                    "Moderate repeat-purchase potential. "
                    "Consider personalized offers or "
                    "targeted marketing campaigns."
                )

            else:

                st.warning(
                    "Low repeat-purchase potential. "
                    "Consider a re-engagement campaign, "
                    "discount, or personalized promotion."
                )


        # ====================================================
        # CUSTOMER INFORMATION
        # ====================================================

        st.subheader("Customer Information")

        display_data = input_data.T.rename(
            columns={0: "Value"}
        )

        st.dataframe(
            display_data,
            use_container_width=True
        )


        # ====================================================
        # PREDICTION LOGGING
        # ====================================================

        log_data = input_data.copy()

        log_data["prediction"] = int(prediction)

        if probability is not None:

            log_data["repeat_purchase_probability"] = (
                float(probability)
            )

        else:

            log_data["repeat_purchase_probability"] = None


        # Add model version to the log
        log_data["model_version"] = metadata.get(
            "model_version",
            "unknown"
        )


        # Add model name
        log_data["model_name"] = metadata.get(
            "model_name",
            "unknown"
        )


        # Add timestamp
        log_data["timestamp"] = datetime.now().isoformat()


        # ====================================================
        # SAVE LOG
        # ====================================================

        if LOG_PATH.exists():

            existing_logs = pd.read_csv(LOG_PATH)

            updated_logs = pd.concat(
                [existing_logs, log_data],
                ignore_index=True
            )

        else:

            updated_logs = log_data


        updated_logs.to_csv(
            LOG_PATH,
            index=False
        )


        st.success(
            "✅ Prediction successfully logged."
        )


        # Show which model generated the prediction

        st.caption(
            f"Prediction generated by model "
            f"**{metadata.get('model_version', 'N/A')}**"
        )


    except Exception as e:

        st.error("❌ Prediction failed.")

        st.exception(e)


# ============================================================
# PREDICTION HISTORY
# ============================================================

st.divider()

st.subheader("📊 Prediction History")


if LOG_PATH.exists():

    logs = pd.read_csv(LOG_PATH)

    st.write(
        f"Total predictions logged: **{len(logs)}**"
    )

    st.dataframe(
        logs.tail(20),
        use_container_width=True
    )

else:

    st.info(
        "No predictions have been logged yet. "
        "Make a prediction to create the prediction log."
    )
