import streamlit as st
import pandas as pd
import joblib
from pathlib import Path


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Retail Customer 360",
    page_icon="🛍️",
    layout="wide"
)


# ============================================================
# TITLE
# ============================================================

st.title("🛍️ Customer Insights & Repeat Purchase Predictor")

st.markdown(
    "Interactive Machine Learning dashboard for the Online Retail dataset."
)


# ============================================================
# LOAD TRAINED MODEL
# ============================================================

MODEL_PATH = Path("models/v1/best_model_pipeline.pkl")


@st.cache_resource
def load_model():
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Model file was not found at: {MODEL_PATH}"
        )

    return joblib.load(MODEL_PATH)


try:
    model = load_model()
except Exception as e:
    st.error("❌ Failed to load the trained model.")
    st.exception(e)
    st.stop()


# ============================================================
# SIDEBAR - CUSTOMER INPUTS
# ============================================================

st.sidebar.header("Customer Parameter Inputs")

st.sidebar.markdown(
    "Enter the customer's historical purchasing behavior."
)

recency_days = st.sidebar.number_input(
    "Recency Days",
    min_value=0.0,
    value=30.0,
    step=1.0,
    help="Number of days since the customer's last purchase."
)

frequency = st.sidebar.number_input(
    "Total Orders",
    min_value=1.0,
    value=5.0,
    step=1.0,
    help="Number of orders made by the customer."
)

total_items = st.sidebar.number_input(
    "Total Items Purchased",
    min_value=1.0,
    value=250.0,
    step=1.0,
    help="Total number of items purchased."
)

total_revenue = st.sidebar.number_input(
    "Total Revenue",
    min_value=0.0,
    value=1000.0,
    step=10.0,
    help="Total historical revenue generated by the customer."
)

average_transaction_value = st.sidebar.number_input(
    "Average Transaction Value",
    min_value=0.0,
    value=200.0,
    step=10.0,
    help="Average value of a customer's transaction."
)

unique_products = st.sidebar.number_input(
    "Unique Products",
    min_value=1.0,
    value=20.0,
    step=1.0,
    help="Number of different products purchased."
)

return_count = st.sidebar.number_input(
    "Return Count",
    min_value=0.0,
    value=0.0,
    step=1.0,
    help="Number of returned transactions/items."
)

lifetime_days = st.sidebar.slider(
    "Customer Lifetime (Days)",
    min_value=0,
    max_value=730,
    value=180,
    help="Number of days between the customer's first and last purchase."
)


# ============================================================
# MAIN SECTION
# ============================================================

st.subheader("Model Prediction")

st.write(
    "Predict whether this customer is likely to make a repeat purchase."
)


# ============================================================
# PREDICTION
# ============================================================

if st.button("🔮 Predict Repeat Purchase", type="primary"):

    # IMPORTANT:
    # These column names must match the features used during training.

    input_data = pd.DataFrame(
        {
            "recency_days": [recency_days],
            "frequency": [frequency],
            "total_items": [total_items],
            "total_revenue": [total_revenue],
            "average_transaction_value": [average_transaction_value],
            "unique_products": [unique_products],
            "return_count": [return_count],
            "lifetime_days": [lifetime_days],
        }
    )

    try:

        # Make prediction
        prediction = model.predict(input_data)[0]

        # Probability, if supported by the model
        probability = None

        if hasattr(model, "predict_proba"):
            probability = model.predict_proba(input_data)[0][1]

        st.divider()

        # ====================================================
        # RESULT
        # ====================================================

        if prediction == 1:

            st.success(
                "✅ **Likely to make a repeat purchase**"
            )

        else:

            st.warning(
                "⚠️ **Unlikely to make a repeat purchase**"
            )

        # ====================================================
        # METRICS
        # ====================================================

        if probability is not None:

            col1, col2 = st.columns(2)

            with col1:
                st.metric(
                    "Repeat Purchase Probability",
                    f"{probability:.1%}"
                )

            with col2:
                st.metric(
                    "Prediction",
                    "Repeat Purchase"
                    if prediction == 1
                    else "No Repeat Purchase"
                )

            st.progress(float(probability))

        # ====================================================
        # CUSTOMER DATA
        # ====================================================

        st.subheader("Customer Information")

        display_data = input_data.T.rename(
            columns={0: "Value"}
        )

        st.dataframe(
            display_data,
            use_container_width=True
        )

    except Exception as e:

        st.error("❌ Prediction failed.")
        st.exception(e)
